export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  EMAIL_REGISTERED = 'EMAIL_REGISTERED',
  USERNAME_EXISTED = 'USERNAME_EXISTED',
  USER_NOT_EXISTED = 'USER_NOT_EXISTED',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
}
